[package]
name = "chip_8"
version = "0.1.0"
authors = ["marin postma <postma.marin@protonmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
v_display = {git = "https://github.com/MarinPostma/V_Display.git"}
itertools = "0.8.0"
clap = "2.33.0"
